name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build the project
        run: cargo build --verbose --release

      - name: Generate version and filename
        id: generate_vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION="$(date +'%Y%m%d')-$(echo $GITHUB_SHA | cut -c1-7)"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FILENAME=filtered-contacts-${VERSION}.csv" >> $GITHUB_ENV

      - name: Run the contact filter
        run: |
          ./target/release/contactfilter input_baofeng_dm32uv.csv countries.txt "${{ env.FILENAME }}"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.FILENAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - name: Create Pre-release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.FILENAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          name: Nightly Build ${{ env.VERSION }}
          prerelease: true
          allowUpdates: true
